### ISSUE TITLE
Is it possible to send a reset instead of dropping the packet?

### ISSUE THREAD

**Issue by koraybilgi** [jsimonetti/sniqueue#20]
Hi @jsimonetti,

Thank you very much for your work.

I'm not very familiar with Golang. Is there a way to send "TCP reset" and/or "ICMP port unreachable" instead of dropping the packet to prevent the client and the daemon from a resend cycle?

**Comment by koraybilgi** [comment]
I noticed that this was an iptables (which I'm using instead of nft) issue and should be deleted. Sorry for the inconvenience.

**Comment by jsimonetti** [comment]
Hi, thank you for the question. As you noticed, sniqueue only marks packets. It is up to your nftables or iptables setup to do something with those marks.

the example nftables.conf rejects bad sni packets and stores its destination in an ipset, which is then used as a cache to reject future packets to the same ip.
